- type: MEMBERSHIP_INFERENCE_ATTACK # 攻击类型
  # 攻击的名称
  name: BASELINE # 参考 PrivBox/examples/membership_inference/rule_base_with_cifar10/README_cn.md 的攻击说明
  # 攻击相关参数
  args:           
    # 测试数据集，包含目标模型的[成员数据集， 非成员数据集]
    test_datasets: [./example/datasets/cifar10_train,
                    ./example/datasets/cifar10_test]
    # 目标模型
    target_model: ./example/models/resnet18_10classes
    
- type: MEMBERSHIP_INFERENCE_ATTACK # 攻击类型
  # 攻击的名称
  name: ML-LEAK # 参考 PrivBox/examples/membership_inference/ml_leaks_with_cifar10_cifar100/README_cn.md 的攻击说明
  # 攻击相关参数
  args:           
    # 目标模型的[成员数据集， 非成员数据集]
    target_datasets: [./example/datasets/cifar10_train,
                    ./example/datasets/cifar10_test]
    # 目标模型
    target_model: ./example/models/resnet18_10classes
    # 使用的影子模型名称
    shadow_model: ./example/models/resnet34_100classes
    # 用来训练影子模型的[成员数据集、非成员数据集]
    shadow_datasets: [./example/datasets/cifar100_train,
                    ./example/datasets/cifar100_test]
    # 影子模型的训练epoch数
    shadow_epoch: 10
    # 影子模型训练用的学习率
    shadow_lr: 0.0002
    # 攻击模型训练的epoch
    classifier_epoch: 10
    # 攻击模型使用的lr
    classifier_lr: 0.0002
    # 训练、预测的batch size
    batch_size: 128
    # 训练攻击模型使用的输出向量top k个
    topk: 3
